version: "3.2"
services:
  php:
    build: './php/'
    volumes:
      - ./project/:/var/www/html/
  nginx:
    image: nginx:latest
    depends_on:
      - php
      - mysql
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./project/:/var/www/html/
  mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: agata
      MYSQL_PASSWORD: agata